### ISSUE TITLE
new recipe: Butter

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#102]
why? because it would be useful for lots of other recipes like say Toast, or Baked Potato

i think it could be made with just Milk, similar to cheese, but maybe with less (like 4 or 5?). also similar to cheese, we can add a rainbow variety.

**Comment by jeremyckahn** [comment]
I dig it! I think the game needs more "base" ingredients for n-tier dishes. So for instance, Milk makes Butter, Butter makes Cookies, and Cookies make Ice Cream Sandwiches, etc.
