### ISSUE TITLE
shop item: Salt

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#103]
why? adding salt to the shop would introduce the idea of things for sale that are used in the workshop for making other things, instead of just supplies/tools for the farm. salt could be useful in many recipes, such as the Baked Potato I mentioned in the butter issue, or making preserved items like sauerkraut.

**Comment by jeremyckahn** [comment]
I think the idea of salt makes sense, but I'm not sure how I feel about salt being generally available in the shop. That is, I'm not sure that base recipe ingredients should be regularly-purchasable items. I think it would be more interesting if base ingredients were obtained through some other mechanism. For instance, what if there was some mining aspect of the game, and salt was one of the ingredients that could be mined for?

I realize that this massively blows out the scope of this feature, but I think it's an idea worth exploring. What do you think about first developing a mining aspect to the game?

Brief aside on this: We don't necessarily need to build an entirely new wing of the game for mining, we could try building it into the Field (for instance).

**Comment by lstebner** [comment]
totally into mining! spun up a discussion https://github.com/jeremyckahn/farmhand/discussions/105 for talking about it

**Comment by lstebner** [comment]
i'm actually going to close this since we don't want to proceed with salt being a shop item, and we have some good ideas in the mining discussion to work on!
