### ISSUE TITLE
new crop: Jalapeño

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#104]
I think this would be a good next addition because it has a really distinct shape that would work well with the game's art style, and also would work well with some of the other available crops for new recipes such as Salsa (onion + tomato + corn + jalapeño), or spicy queso (cheese + jalapeño).

proposed growth stages: 1 days seed, 2 days sprout (leafy), 2 days growing pepper. 5 days total
proposed tier: 2

**Comment by jeremyckahn** [comment]
Agreed! +1 to this idea. 🌶

One suggestion: It think we should make this a tier 4 crop. I like the idea of each tier having three crops each to give a smoother sense of progression.
