### ISSUE TITLE
new Soybean recipes

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#109]
a few things I think we could add related to those tasty, tasty Soybeans (adding at least one that is blocked by #108 - mining)

Soy Milk:
- ingredients: 10 soy beans
- unlock reqs: sell 100 soy beans

Chocolate Soy Milk:
- ingredients: 1 soy milk, 1 chocolate
- unlock reqs: sell 

Edamame:
- ingredients: 8 soy beans, 1 salt*
- unlock reqs: sell 56 soy beans, sell 8 salts

Tofu:
- ingredients: 4 soy milk
- unlock reqs: sell 20 soy milks

**Comment by jeremyckahn** [comment]
This gets a 👍 from me! I love the vegan(ish) theme. 🙂🌱
