### ISSUE TITLE
increase Cheese unlock requirements

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#115]
now that Butter has been added, the Cheese one is a little out of balance since it requires more to make, but less to unlock. up'ing it to 42 would make it the same ratio. This is a very small change so I will wait for @jeremyckahn to approve the new value before making the change

**Comment by jeremyckahn** [comment]
Sounds good to me! 42 is the meaning of life, after all! 🙃

**Comment by lstebner** [comment]
was just looking over the oldest issues and i'm thinking this one can probably just be closed. i don't see a lot of value in making this change

**Comment by jeremyckahn** [comment]
Agreed! We can always revisit this later.
