### ISSUE TITLE
add Jalapeño recipes

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#120]
I thought of 3 recipes to add around the new crop.

1. Hot Sauce; ingredients- 10 jalapeño; unlocks after selling 50 jalapeño
2. Salsa; ingredients- 1 jalapeño, 1 onion, 1 tomato, 1 corn; unlocks after selling 5x of each ingredient
3. Spicy Cheese; ingredients 4 jalapeño, 1 cheese; unlocks after selling 20 jalapeño and 5 chees

**Comment by jeremyckahn** [comment]
Awesome ideas! I’m into it! 👍🌶

**Comment by lstebner** [comment]
<img width="571" alt="Screen Shot 2021-06-18 at 9 31 43 AM" src="https://user-images.githubusercontent.com/628757/122591633-0f55b600-d018-11eb-8942-46cf3cba6c65.png">

work in progress :)
