### ISSUE TITLE
Smelter

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#163]
Add the Smelter. This item will be available in the shop after the shovel is unlocked, and required for workshop items involving ores. 

We'll need to figure out a good cost for this item that fits with the other shop items

**Comment by jeremyckahn** [comment]
I think this should have a medium cost of entry, maybe $15,000 or so. Having this become accessible around day 50 (in terms of how much money players might have) feels appropriate to me. I'd like to get others' thoughts on this too!
