### ISSUE TITLE
Ingots

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#164]
Add the ability to make ingots using the smelter and ores. This might need a few more details before being worked on and is blocked by #163

**Comment by jeremyckahn** [comment]
Just to throw an idea out there, it might be worth having a dedicated "blacksmithing" page similar to how we have it for recipes just to give all of the new forging mechanics a home in the UI. I'll hold off on making a ticket for this now, as I think some of the related ideas need to be more fleshed out first.

**Comment by lstebner** [comment]
i've filed #177 which I think covers what you were thinking about @jeremyckahn . i can think of a few names, "forge", "blacksmith shop", or just "smelter". no strong preference for me

**Comment by lstebner** [comment]
also i added the ingot recipes without really thinking about it as part of PR #176 so i think i can just finish them there and we don't need this issue at all

**Comment by jeremyckahn** [comment]
> also i added the ingot recipes without really thinking about it as part of PR #176 so i think i can just finish them there and we don't need this issue at all

Nice! I think it's fine to leave this open for now and close it out along with #163 when the PR is merged.
