### ISSUE TITLE
Coal

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#165]
add the item Coal to be used for smelting. as part of this, i think we'll want to update the recipes for the ingots to require some coal as well

**Comment by jeremyckahn** [comment]
We'll definitely need coal to tie together the overall mining features. I'm wondering how this might relate to #116. In some games (like Forager), coal is made from trees that were chopped down. I think that could work well for Farmhand, assuming we have trees.

#116 doesn't need to block the addition of coal, though. For a first iteration, coal could just be dug up from mined plots (I think Stardew Valley works this way).

**Comment by lstebner** [comment]
i think multiple sources for coal makes sense. we can also look at it like there are different ways to fuel the forge in general, so we could even introduce other stuff one day. stardew valley has a clever way of making batteries from captured lightning that comes to mind for a similar example.
