### ISSUE TITLE
Improve nonsighted accessibility of keyboard shortcut modal

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#175]
> Per @worry on Discord, this should use some sort of accessibility affordance (such as [`aria-describedby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute)) to inform non-sighted users about the availability of this modal.

_Originally posted by @jeremyckahn in https://github.com/jeremyckahn/farmhand/issues/172#issuecomment-897643802_

**Comment by lstebner** [comment]
I am pretty sure the requirement here is to add an `id` to the `h2` element that inside of the modal, and then to use that as the `aria-describedby` value for the modal. so it would be something like:

```
<div class="the-modal" aria-describedby="hotkeys-modal-heading">
   <h2 id="hotkeys-modal-heading">Keyboard Shortcuts</h2>
   ...
```
