### ISSUE TITLE
add Smelter area to Workshop

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#177]
once the Smelter is purchased it should be a separate  "area" (tab maybe?) of the workshop. this interface might take a little bit of design to sort out, or maybe MUI provides something already.

**Comment by jeremyckahn** [comment]
Per @lstebner [on Discord](https://discord.com/channels/714539345050075176/878706542604591124/878728088136060978):

>i wonder if we should flip “recipes” and “workshop”. everything that is made could be seen as “recipes” and then the tabs are sorta like locations of the farm to craft in. maybe forge and workshop to start? or forge and kitchen? since it is mainly foods

My response:

>I think breaking the tabs down into "forge" and "kitchen" makes sense!

**Comment by jeremyckahn** [comment]
@lstebner were you envisioning anything beyond a tabbed space for Forge recipes? Do you think we need some additional bit of UI that the Kitchen area doesn't have?

<img width="397" alt="Screen Shot 2021-08-22 at 7 04 06 PM" src="https://user-images.githubusercontent.com/366330/130374645-682f544e-c3a6-438e-afb3-2559b194b86c.png">

**Comment by lstebner** [comment]
> @lstebner were you envisioning anything beyond a tabbed space for Forge recipes? Do you think we need some additional bit of UI that the Kitchen area doesn't have?

hmm the only thing that this makes me think of is an area to insert fuel that could be outside of any recipe, but we could also just make recipes require some fuel. either way.. i think it's scope creep for this PR so I wouldn't worry about it. let's discuss for the mining feature in general. this is looking great!

**Comment by jeremyckahn** [comment]
Thanks for spot-checking this @lstebner! I agree with reining in the scope here — I'd like this ticket to be about setting up a space in the UI for Forge recipes. Let's continue to discuss what will go here in a separate thread!

As you pointed out [on Discord](https://discord.com/channels/714539345050075176/878706542604591124/879199622772432937), tab navigation is currently broken so I'd like to fix that if I can before opening a PR, as well as maybe some code cleanup.

**Comment by jeremyckahn** [comment]
Ugh I just realized that MUI tabs expect you to use the left/right arrow keys to move between tabs, but that clashes with Farmhand's global left/right view switch key handlers. I'll have to look into whether we can use a tab-based navigation here, or perhaps intelligently disable the global left/right key handler. 😕

**Comment by jeremyckahn** [comment]
The keyboard navigation issue wound up being an easy fix: https://github.com/jeremyckahn/farmhand/commit/2a2e187e17eb2f86e2bc959ea2a3b1990a2eb2c4
