### ISSUE TITLE
The Bread Crisis

### ISSUE THREAD

**Issue by MaggiMiner** [jeremyckahn/farmhand#23]
the price of Bread (or any other end product) is fixed, i can sell 1 bread for $525, that costs 15 wheat, when wheat is more then $35, then the end product (bread) has less value then its ingredients (wheat).

**Comment by jeremyckahn** [comment]
(note to self)

Relevant section of code: https://github.com/jeremyckahn/farmhand/blob/b5acd9ec0689296db9e66e55de87a14ebe15234a/src/data/recipes.js#L16-L23

**Comment by jeremyckahn** [comment]
Oh, actually this is working as designed. The whole idea of the recipe pricing structure is that recipes are priced at a [constant 125%](https://github.com/jeremyckahn/farmhand/blob/e7ad89c5b359759279ad24cd7504c77e9a586d99/src/constants.js#L105) of their sum ingredients' values. Internally, [crop values fluctuate between 50% and 150% of their base value](https://github.com/jeremyckahn/farmhand/blob/e7ad89c5b359759279ad24cd7504c77e9a586d99/src/common/utils.js#L10-L17). Among other things, recipes offer a stable mechanism of getting a good (though not optimal) value out of crops regardless of market conditions. 

Additionally, this algorithm works out such that secondary recipes (like [French Onion Soup](https://jeremyckahn.github.io/farmhand/docs/farmhand.module_recipes.html#.frenchOnionSoup)) are also a stable 125% of their ingredients ([Cheese](https://jeremyckahn.github.io/farmhand/docs/farmhand.module_recipes.html#.cheese) and [Onion](https://jeremyckahn.github.io/farmhand/docs/farmhand.module_items.html#.onion), in this case), so the value of the [Grade A Milk](https://jeremyckahn.github.io/farmhand/docs/farmhand.module_items.html#.milk3) that went into the Cheese is effectively multiplied by 1.25 twice, making those more difficult recipes particularly lucrative.
