### ISSUE TITLE
Can't make soup if you're broke

### ISSUE THREAD

**Issue by thatsanicehat** [jeremyckahn/farmhand#25]
I couldn't afford a carrot seed, but had some carrots. Once I sold a few individual carrots and wasn't entirely broke, I could make soup again! 

![Screen Shot 2021-03-15 at 9 20 18 PM](https://user-images.githubusercontent.com/10038391/111255541-81130380-85d4-11eb-877d-0dec36d08817.png)

**Comment by thatsanicehat** [comment]
Okay nope, my inventory was full.

**Comment by jeremyckahn** [comment]
> Okay nope, my inventory was full.

In that case, the quantity line shouldn’t read “3/14.” If you can reproduce the state that’s pictured, could you export your data (from the settings screen) and attach it to this issue so I can debug it?

I’m thinking that the logic that determines yield capacity might be broken. 😬

**Comment by jeremyckahn** [comment]
Relevant part of the code: https://github.com/jeremyckahn/farmhand/blob/e12b63e89ded51307499bf24dd775e2aaa347fd9/src/utils.js#L517-L532

**Comment by jeremyckahn** [comment]
This may also need to be revisited: https://github.com/jeremyckahn/farmhand/blob/e12b63e89ded51307499bf24dd775e2aaa347fd9/src/utils.js#L534-L541

**Comment by jeremyckahn** [comment]
Deeper down the rabbit hole: https://github.com/jeremyckahn/farmhand/blob/e12b63e89ded51307499bf24dd775e2aaa347fd9/src/components/Recipe/Recipe.js#L72-L75

I think this logic can be tweaked a bit to fix this!
