### ISSUE TITLE
Give new players a Scarecrow

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#259]
Suggested by @lstebner [on Discord](https://discord.com/channels/714539345050075176/722286738344640552/950144300757434428):

> it might be nice to give players a scarecrow in their initial inventory. i often go to the shop and just buy up as many seeds as i can, then get pretty bummed when i realize i need a scarecrow and can't afford it. it would ease the learning curve a little so that it becomes an item you replace, not acquire then lose

**Comment by karlerik-simon** [comment]
I would be happy to work on this issue!

**Comment by jeremyckahn** [comment]
@karlerik-simon awesome! Have at it and feel free to open a PR. Let me know if you have any questions! Also, all of the devs hang out in [the Discord server](https://discord.gg/6cHEZ9H), so feel free to join us there as well.

**Comment by karlerik-simon** [comment]
Thanks, perfect, will join right away!
