### ISSUE TITLE
Minor UI improvements to cow sorting

### ISSUE THREAD

**Issue by thatsanicehat** [jeremyckahn/farmhand#26]
The first thing I want to do when there's a new little cow baby is hug them. But I have to find them first! If the default sort was by age, ascending, or if the game remembered my last choice, this would save a bit of hassle!

**Comment by jeremyckahn** [comment]
Yeah that UX bugs me too. Thanks for filing the issue to track this! I’ll label and prioritize. :)

**Comment by AbinashWorlds** [comment]
Hey @thatsanicehat trying joining our discord server as well in case you have any questions left to ask! In case you already are in the server ignore my message 😅

**Comment by jeremyckahn** [comment]
Oh whoops, I actually fixed this in https://github.com/jeremyckahn/farmhand/commit/1f62ca27a4761c1e0ac0318b36e2bc2a9f2e0139 and forgot about this issue. Sorry about that! Now cows are sorted by ascending age by default. 🐮

<img width="334" alt="Screen Shot 2021-03-24 at 8 30 57 PM" src="https://user-images.githubusercontent.com/366330/112405388-29fde480-8ce0-11eb-8082-6436cf11d763.png">
