### ISSUE TITLE
Use `getSalePriceMultiplier` to render item prices

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#264]
Per the TODO here: https://github.com/jeremyckahn/farmhand/blob/9e9997d81291311ffb86b90daf6fe32f9426cee5/src/utils.js#L1118-L1135

**Comment by lstebner** [comment]
i think this is done? the inventory is using this util for sure, but is there somewhere else you had in mind?

**Comment by jeremyckahn** [comment]
I think you're right, this ticket is no longer needed. After taking another look at this, I noticed an opportunity to do a bit of refactoring. I'll assign this to myself to take care of and close out.

**Comment by jeremyckahn** [comment]
On second thought I think the code is fine as-is. I'm going to remove the `TODO` and close this issue out.
