### ISSUE TITLE
Define smoke test process

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#281]
Define a smoke test process that any player can perform to ensure stability. Tasks should be relatively high-level and avoid being overly prescriptive to allow for a degree of spontaneity during testing. This spontaneity should hopefully result in wider test coverage.

**Comment by lstebner** [comment]
was thinking about this so figured I might as well leave my thoughts here rather than just in my head.

- starting from a brand new game
    - [ ] can purchase seeds from shop
    - [ ] can plant a seed
    - [ ] can plant seeds with different range settings
    - [ ] can water seeds
    - [ ] empty plots don't get watered
    - [ ] can hoe seeds
    - [ ] can end the day
    - [ ] reloading the page resumes the game in progress
    - [ ] can purchase storage upgrades
    - [ ] can't store more than storage allows
    - [ ] can purchase cowpen
    - [ ] can purchase cows
    - [ ] can offer cow for trade
    - [ ] can harvest grown crops
    - [ ] can sell grown crops
    - [ ] recipes unlock from selling crops
    - [ ] can make recipes
    - [ ] can sell crafted recipes
    - [ ] can hug cows
    - [ ] can level up

late game / mining features probably need a save to load to test efficiently
    - [ ] combine auto harvests crops
    - [ ] shovel unlocks at level 6
    - [ ] can purchase smelter
    - [ ] can dig empty plots with the shovel
    - [ ] plots with crops don't get shoveled
    - [ ] can sell mined items
    - [ ] can craft ores
    - [ ] can craft tool upgrades
    - [ ] <insert some tests for each upgraded tool to make sure they do what they're supposed to>
    - [ ] cannot have more cows than cowpen allows
    - [ ] can breed cows
    - [ ] cow offspring have correct traits
    - [ ] can breed rainbow cow
    - [ ] can pay off loan


that's everything off the top of my head! there's probably more stuff even, but I went by memory here :smile:
