### ISSUE TITLE
Notification alert spam

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#33]
Notification alert spam doesn't stop, you have to reload sometimes

Via @AbinashWorlds

**Comment by AbinashWorlds** [comment]
> Notification alert spam doesn't stop, you have to reload sometimes
> 
> Via @AbinashWorlds

Can't we just remove that? Like make an inbox if people want to read the green and yellow ones?
****Keep only red ones those are necessary****

**Comment by jeremyckahn** [comment]
> Can't we just remove that? Like make an inbox if people want to read the green and yellow ones?

I can add a toggle to hide notifications completely, but that will have to come later.
