### ISSUE TITLE
Garlic bread

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#374]
Add garlic bread recipe.

**Comment by OrangeDuk** [comment]
Fixed Version
This art was provided by orange on Discord[orange on Discord](https://discord.com/channels/714539345050075176/1062561823733325834/1063074141835636737) :

**Comment by OrangeDuk** [comment]
Fixed Version
This art was provided by orange on D[orange on Discord](https://discord.com/channels/714539345050075176/1062561823733325834/1063074141835636737) 
![garlic_bred_2](https://user-images.githubusercontent.com/122408318/212069176-c2494418-b63f-4696-9e14-1f1b23703945.png)
iscord:

**Comment by lstebner** [comment]
this was completed with #377
