### ISSUE TITLE
Please migrate away from typeface-public-sans so it can be unpublished

### ISSUE THREAD

**Issue by grubersjoe** [jeremyckahn/farmhand#531]
Hey. I'm the maintainer of the npm package [typeface-public-sans](https://www.npmjs.com/package/typeface-public-sans) this project uses. This package is deprecated since several years and I wanted to unpublish it now. This project is the final one depending on typeface-public-sans and I cannot delete the package as long as there are dependents.

Could you help me with this and use [Fontsource Public Sans](https://www.npmjs.com/package/@fontsource/public-sans) as a drop-in replacement instead? I would appreciate that a lot. Thank you.

**Comment by jeremyckahn** [comment]
Hi @grubersjoe, thanks for all your work on `typeface-public-sans`! I'm happy to address this and will prioritize removing it from Farmhand just as soon as I can.

**Comment by jeremyckahn** [comment]
[1.18.25](https://github.com/jeremyckahn/farmhand/releases/tag/1.18.25) has been published, which no longer includes any `typeface-*` packages. @grubersjoe let me if everything looks good to you!

**Comment by grubersjoe** [comment]
Thanks for the quick implementation :)!
