### ISSUE TITLE
Achievement: I am rich

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#73]
This is the original idea that was contributed:
Reach $1,000,000
(will help speedrunners to save time)
Reward: 10% extra online time money reward

I think we should split this up into at least 2 achievements, maybe 3. I'm unsure what proper rewards would be so these are just ideas:

1. Highest Tax Bracket
how to get: Reach $518,401
reward: all sale prices increase 5%

2. Millionaire
how to get: Reach $1,000,000
reward: all sale prices increase 10%

3. Billionaire
how to get: Reach: $1,000,000,000
reward: all sale prices increase 25%

**Comment by jeremyckahn** [comment]
I really like the tiers here, I think it gets us a bit more mileage out of the core idea of @AbinashWorlds' original suggestion. I'd like to tweak the lowest tier a bit, as I don't know that the joke is quite universal (it's pretty America-centric). I think lowering the goal to $500,000 and calling it something like "Road to Riches" might have a broader appeal.

**Comment by jeremyckahn** [comment]
Implementation notes for this:

  - To create an achievement, add an entry to this array: https://github.com/jeremyckahn/farmhand/blob/3a3354a1394c3ad80cc2b872375558917a767f08/src/data/achievements.js#L33-L244
  - To boost the money earned from a sale, this reducer function will probably need to be modified: https://github.com/jeremyckahn/farmhand/blob/3a3354a1394c3ad80cc2b872375558917a767f08/src/reducers.js#L1111-L1170

**Comment by lstebner** [comment]
haha yes i like "road to riches" and the $500k point for that. thanks for the code pointers! will be back with a PR for this

**Comment by lstebner** [comment]
I added the new achievement definitions in the commit that just got linked, but on the other end of it.. it seems like we would want the price shown before selling to show the increased value, but I think this requires adding something to `getItemCurrentValue` and/or `valueAdjustments`. the way i've implemented it does increase the sales value (i left a console.log in place for quick and dirty testing). could use some advice whenever you can look at the commit @jeremyckahn  and then I'll add some unit tests before finalizing a PR

**Comment by lstebner** [comment]
actually i went ahead and added a few unit tests to the achievements spec to start. i'm curious what you think of the style though @jeremyckahn . it's a little different than the other one in there, but it looks like we need to add some more coverage :). draft PR 👉 https://github.com/jeremyckahn/farmhand/pull/77/
