### ISSUE TITLE
Consolidate all of the crow notifications into a single one

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#76]

**Comment by lstebner** [comment]
this is the same as #42 i believe @jeremyckahn . i typically keep the lower ID'd issue when i find duplicates, but flagging for you to decide :)

**Comment by jeremyckahn** [comment]
> this is the same as #42 i believe @jeremyckahn . i typically keep the lower ID'd issue when i find duplicates, but flagging for you to decide :)

It is, yeah. I like the approach of keeping the lower GitHub IDs, it gives the earlier requestor more credit.

Closing this!
