### ISSUE TITLE
bug with number inputs on mobile device

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#98]
when on my phone, i can't enter numbers into the number inputs. whenever i try to delete the initial 1, the cursor moves to the left of it instead, and then typing in new numbers results in the 1 always being at the end. i.e. i try to enter '20' and i get '201'. it seems impossible to actually enter digits into here. i'll get a video of this bug if needed, but it seems easy to recreate for me via any of the buy or sell quantity inputs

**Comment by jeremyckahn** [comment]
Yeah, the UX for these inputs leave a lot to be desired. They do work on mobile (you need to double-tap to Select All and then overwrite), but they could be a lot better. There's a related card on the Idea Board and I just linked it to this issue: https://github.com/jeremyckahn/farmhand/projects/1#card-61674937

**Comment by jeremyckahn** [comment]
With #121 merged, do we want to close this issue? It doesn't quite fix the problem as stated, but it implements a reasonable workaround.

**Comment by lstebner** [comment]
sorry for not responding sooner, but i can safely say after using the updated version my initial complaints are resolved. the UI/UX is much better now!
